### ISSUE TITLE
#96 circle ci のテストが失敗する

### ISSUE THREAD

**Issue by H37kouya** [aiirononeko/languageMemoApp#105]
https://github.com/aiirononeko/languageMemoApp/pull/96#issuecomment-622941996

**Comment by H37kouya** [comment]
Cricle ciのテストが失敗する原因は、

Windowsだと、ファイルの大文字小文字を区別しないが、Unixはファイルの大文字小文字を区別するから

**Comment by aiirononeko** [comment]
了解です！調査ありがとうございます！！
