### ISSUE TITLE
画像アップロード時のエラー

### ISSUE THREAD

**Issue by Kanezoh** [aiirononeko/languageMemoApp#135]
![スクリーンショット 2020-05-20 8 57 01](https://user-images.githubusercontent.com/47489839/82389756-ea3eee80-9a77-11ea-9e04-429a782b7cad.png)

フロントでプロフィールの編集画面から画像を更新しようとすると画像のようなエラーが出ます。

気になる点

1. `Parameters: {"avatar"=>~ "registration"=>{"avatar"=>"~}
`
のように、registrationがリクエストに含まれていてunpermitted errorを出している。

2. can't verify csrf token

原因がフロントかバック、またはその両方の可能性があるけどとりあえず以下の記事が参考になりそうです。https://qiita.com/yu_suke1994/items/39fa64ef96aa2a67dc2a

3. `ActiveSupport::MessageVerifier::InvalidSignature`というエラーが出ている。

3に関しては調べたところformに`enctype="multipart/form-data"`を入れれば解決できそうです。
参考：https://stackoverflow.com/questions/50483901/rails-activestorage-error-messageverifier-invalidsignature

**Comment by show-coco** [comment]
1に関してはバックエンドでしか修正できない可能性があります
僕はregistrationsを設定していないので多分ですが。

[evise: Unpermitted parameters](https://stackoverflow.com/questions/35668465/devise-unpermitted-parameters)

2 に関しては調査してみます

3に関してはformに入れたらローカルでは解決しました！

**Comment by Kanezoh** [comment]
ありがとうございます。とりあえずこちら側では1の問題の解決法を模索してみます

**Comment by Kanezoh** [comment]
ローカル環境での検証には成功しましたがGCPへのアップロードはまだ検証できてないのでこのissueはまだ残しておきます。

**Comment by H37kouya** [comment]
------WebKitFormBoundarygZgoEQxU9DVpots9
Content-Disposition: form-data; name="address"


------WebKitFormBoundarygZgoEQxU9DVpots9
Content-Disposition: form-data; name="avatar"

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIEAAACACAYAAAAs/Ar1AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAC0NJREFUeNrsnUtsG9cVhg/JISk+JJmyJD9kB7bcxO92kVhFgxYwardZBCjQAkkKLwq03RTosovugq67CpIWBQo0BYoiaNA2AdwYRevXym4svxRHfkiRSYGWrBctihLfMyR7z6UpUxQpzpAz1L3k+YELEhQfo3u+Oee/Z4YcZWpq6jQAXAVSx8pOU0AiCEgEAYkgIBEEJIKARBCQCAISQUAiCEgEAYkgIBEEJIKAtEFKJ/7T+cX7AGoC8tHQ+mOpLHs8D+DoHgSFDVf/AbC7fARB2wR9dpQFfpwHvzzw5YrHAbJaxeQwGLr2Hgf33hPgPTjStlC0LwRsT9cmPoNc6CoUEosNvYW2tgjxCRxXIXrdB94DI9D72jscDoJAhuBPfgaFbMK8bJJJcBhwYFYIvP6ztoGhrSDAtK/e+MDU4FdTMjTKxw6WFTAzEASC7P3qnQ956m+lVm59DMnpURh449dSZwV7OwCQvfJuywEoKRsJwdw/fgXZZyGCYDsBqOX4W1aGmF9YOP+utCDYCQACQVoIRAJAdhCkhEC7+6FwAJSDsHjxPVCTqwSBZZO8eJ/3AURWbuUJLF3/C2iqShBYYgVufCDHdk5dgWehu1KAIBUE2vjHDbeAt8W33PsnLC8vCQ+CVBBgK1iq0hX5CnKLk8KDIA0E/ECQxe1gS7b7yQ0o5PNCg6DIBEHL9xCXB5yBvdC169D6Y7F7/zW23eEb4DzxIyg4PRyEvr4BUJxOgsC4y0rw8wFaFXjf8Gt8IACVMgoBB2HuHjhe+uZ6RhANBCkg4GcCtSD4vce+A/7D3+b3awnBUKNPDb13YXX2xX0BQZADAosbQ56h4+A98RZoSv0zh7A0GIUgH5vdCIVgIMhhDFXrDOHOkbdh3w9/A4p/p67nY5kwqkJsZvNjAplFuxyZYNqS99119pfQN/KWoddgOXCXGUVdEKip6o8LAkJHnnJud/v43t9z5HRDrw+8+gPTtkUEEOydCgD6gEaF2aD3699vGxDsnQiAu/9A0+/Vc/J7DfkDEUGwEwCNawcrC9V6CbKB0BEQYOAP/uT3pgJQ6i0Mnv2F9Bmh7SHwD5/iGQAzgSUTyEDo+9Y7UnuEtv0GEgZ9J1v+7fjGmy35PPQInn3HIXr7PGQWHpsGQisaSm0JQc/R02z9/zY4uwda+rnoD7A8IASJ4C1IzdyHfDYlPAgKBd8CD7Lr0HpDCVvMCMKqwCBIDYGzZ4CbPd/wCPgPnrKs7jebHbji4pYGRZY93HHgWHGDWeBxT8fgixh0q2QlCHJAcOQ0uJ0F6HRZBQL9XI2kIJi5fCQICASCgEAgCAgEgoBAIAgIBIKAQCAICASCgEAgCAgEuSDIqDapg5Ir2IQGQY7vHUh+2CCftwmdEaSAoPKHp2WTmtu+adYDgjTlQOZskM1tbzmrB4I0xjCVldMXFArbmwn0gCANBIm0nBCkNYfwqwZpIMCSIOMqIaU6hNqeaiBI1SeIJW3SAZDLi7fNlSBIBQFmAlm8AXqBRFbcs/fKQZCuY7iSsEuxUljLODkIQoP6HATpINByAMtrYm82msGMJsfUIghSHjvAkrCWErMsaMwDxDNyfZ1D2gNIWBYSGZtwAKykXMKXgbaBAIVlQRQQZAVAeghKIKwmt/ffwI6grACg2uILqdg/yDIj1tfNTE6LE0OSLQMTWYfU89c2J5WgWZxbdrSsPGD6jyZd0gPQNpmgJOwfcJ+QLkDAp4FTMZ/xAsv58awT0qqjbeatLX+kgncWkynIK3lQXG6wO5xgszWXIfI5DXJs4G06t7Ot5qutr5qez+cgm04W655DAQcbeGuzO+pCga/FRgre4pDW9XUiBBhct9vNori6aU/GseG5djt7frFkZDNJNtI88HUnTVEYGHk+CALBgu/1esDj8RT38rwbCplF5uBq/0QIBrwA+Q17/tYfwqbLPQBeR1dxaaiqkMlkpIehbVYH3d3dDALvizRvZz7AMwQ2735+vznC2DS5mA/A93oOAMrpdILf74dkMkUQbKdCoRBcvnwFxsbGqj/BwcDwDYPNPVgMpuFc6Qfw7McfSKr652g0ChcvXobR0VsQiTyjctAqZbMqTE5OQDAYgkSieC0E3CO3lCsANmdvsUSosfofgnu8M7Bhz6+m5eUov52bm+cDs9Hhw6/Anj27eKYgCExWMByG8PQ0zM1uvvLI2pqOH4ljmcDWtZsDUUgzGHLJ2qlf8evaphKEJSWTSbh7dwzGx50MhN1w4sQx4WEQHoK5SARuP5yA248moN+pQJ/bVfV5S0sRA0XQXfQKLCPwzFDIr2cLUHoMlY35+eoX60TTGA4/gTuTUxAYHICTh4bh5Zf2EQR6FV1bgwcs1WPwn0ZeBNfT5d7ydbOzszA0NKT/g1h5sCndxfLAVhaQMf4tF/QEW8ntcMBkeIaPLpcLTn7tIAdisC9AEFQqzZZa90PTPPj3g9UvfOVRtm7Vrq6ugREG+NIwlYHI7/4K2ndfB+g3FphsNsvHVupyvMgqafbcmw8m+Oj1++DU0SM8O+D9joaAB505/AfBaUgxEGrJ76y/qUtLS3CUTaxuANjSbvG374P6ZBZWpqbA99Mfg8IMnf4ssFI/2djt4GDL1lxFxzEWT8Clm7f5eIWB8PL+ffzW7XJ1BgSY7ot1/hFE2d6rRx5H/QM2kUikIQB44yidhuifPoLAz8/pBmFhYUHX87AkJLXapaZULi5cA1Yuhnm5eGn3YPtCcImtpy+N3jT8ui5FTyaINARASUZBiMf1XarPp2wNQbm+nArygVnhzKlXW1IqWtYswpr//t/+3hAAejMBtnAzW5SUrQCoBEGbWzANArfD+GFnzAx//te/IVxj9SEdBAjAHz89v8HpGxHW1HqmUE9JQECm3/tDTQAqQXj8OGhKOSg3h4bmjRnJj/5zCb4Kz8hfDpoBQM+qoFwzM9WXibhyuHDhAgyNj0NgebOhi+U1UGGjefvf9c/57SFWo40uDfWYQ726cO1zOOc/Y9my0nII0AM0A0BxZaC/47ZaxWiiV/jkk095JuiNLAE8nd/8OsZZte+7Xq8Bgt5SUJKXgbymag1nhEs378C5N87IBwGWgWtf3Gv6fboM1NQIBrkGAKg9R49D//6Dm/dsNQPZikPCD7YAwUgmKP0PjUKACs8v8LJgRdfRUk+AzZ9UHaNmdjkoXyFUAtCMEIRyjzBv0LB5leb3ty/reBQhM8GDYPOXvMda6rIbY7UEglkAVCsNiYSx69m4Hc3vb5MWGURLIQhWOdpnZRYo6eHDh2w8MhWAchDwULZRT4Awo0FUmzwLCZeMZjeSLIXAjFLgb+Aw7NjYF5aa3Vu3bjfobZqHQKo+AbaGzVCXo33O7zfjfwnr7E2IAcGqORA0Ug5ElRnmUKpMYIYaMYUiywxzmKlz6FooCOaabBAZzQJxtgbPbcMXRLDGp3M5Q+awGS0sr5j+P1iWn1KZ5omtZQox4Ck28WmteJvSikE41NOt67wDMxVjK4WldGY93aP5w9qPwfZWgVhEcyj0OYY4kRjwBAabDezolQIuovBwcVLbbAbdz8EojWY6h7F4XB4IgrOzTb/HE4NrcRGFpQJHDMy5hmHMgjmhi16QCAIZZXY2sAwCM1rGJMkhIFE5IFmaCeLiQ0ClwGIIElQOSFQOSGYbQ8uaRWdHTq3fz6RToGmq5ZMTcLvqHnCy9+yATJXrANlyOVAqjj0c6e+t+5kJLaf7iyVmqdfnEx+C4aG9fJRkxuXdTdMBgHSVh21VJuMwlQPzhL8S1tc3AIokv9xBnoBAIAgIBIKAQCAICASCgEAgCAgEgoBAIAgIBIKAQCAICITO1f8FGAD28BcigeM1EgAAAABJRU5ErkJggg==
------WebKitFormBoundarygZgoEQxU9DVpots9
Content-Disposition: form-data; name="profile"


------WebKitFormBoundarygZgoEQxU9DVpots9
Content-Disposition: form-data; name="name"

h37kouya
------WebKitFormBoundarygZgoEQxU9DVpots9--
```
