### ISSUE TITLE
folderの階層構造の実装

### ISSUE THREAD

**Issue by Kanezoh** [aiirononeko/languageMemoApp#144]
folderはネストできるようにしたい。
ネストしたルーティングの定義方法はこれが参考になりそう。
https://stackoverflow.com/questions/30279947/recursive-rails-path

ルーティングとしてはfolders/1/2/3
みたいな感じに並んでいくイメージっぽい。

**Comment by kurehei** [comment]
イメージとしては、こんなイメージですかね？
````
resources :folder do
   get '/folder/*path', :controller => 'files', :action => 'index'
end
````

**Comment by Kanezoh** [comment]
そうですね。パラメータ名は`:folder_id`の方が良いと思います。
このルーティングと合わせてfolderの親子関係を表す中間テーブルを作成、このテーブルにはparent_idとchild_idの2つでUNIQUEを取るのと、親と子が逆の場合でもUNIQUEをかけなきゃいけないですね。(parent_id:1,child_id:2のレコードとparent_id:2,child_id:1のレコードが同時に存在するのはおかしい)
ただ逆の組み合わせを防ぐ制約はDBのデフォルトではないっぽいです。
参考：https://teratail.com/questions/148341

とりあえず最初のDBからモデル関連の設定は僕の担当で大丈夫ですか？

**Comment by kurehei** [comment]
質問なんですけど、中間テーブルにレコードを作成する場合って、どういうイメージですかね？
子folder作成時に、同時に中間テーブルのレコードも作成というイメージであってますかね？

> とりあえず最初のDBからモデル関連の設定は僕の担当で大丈夫ですか？

それでお願いします。

**Comment by Kanezoh** [comment]
そうです、子フォルダー作成時に親フォルダーIDと子フォルダーIDを中間テーブルに保存します。

> それでお願いします。

了解です、今日中に作業します。

**Comment by kurehei** [comment]
controllerと、エンドポイント周りは実装します

**Comment by Kanezoh** [comment]
#157 
途中まででプルリクを作成しました。作っていて気づいたのですが、folderは多対多というより同じモデルにおける一対多の関係なんですよね。
一応今の時点でも```folder.parent_folder```や```folder.child_folders```は使えるんですが、一つしか存在しないはずのparent_folderをhas_manyで作らなければいけません。返ってくるのもサイズが1の配列ですし。
ということでparentに関してはhas_manyで中間テーブルから取得するより、folderで```parent_id```という値を持たせた方が良いと思うのですがどうでしょうか？

**Comment by kurehei** [comment]
確かに同じ階層にいくつもフォルダを作るとした場合親フォルダに対して、子フォルダは一対多の関係になりますね。

> ということでparentに関してはhas_manyで中間テーブルから取得するより、folderでparent_idという値を持たせた方が良いと思うのですがどうでしょうか？

いいと思います。
１つ質問ですがフォルダの階層を作らない場合は、parent_idはnullという事になるにでpostテーブルのfolder_id同様nullを許可するという事で大丈夫ですか？

**Comment by Kanezoh** [comment]
> フォルダの階層を作らない場合は、parent_idはnullという事になるのでpostテーブルのfolder_id同様nullを許可するという事で大丈夫ですか？

そうです。ユーザーが最初にフォルダを作った場合はユーザー直下にディレクトリが作成されるので親がいない、つまりparent_idはNULLになります。

**Comment by kurehei** [comment]
了解です。承知しました。

**Comment by Kanezoh** [comment]
#158 でfolderにparent_idを付加するプルリクを作成しました。
レビューお願いします。🙇‍♂️
