### ISSUE TITLE
sns認証をできるようにする

### ISSUE THREAD

**Issue by H37kouya** [aiirononeko/languageMemoApp#196]
# SNS認証をできるようにする

- [ ] Twitter
- [ ] Google (google_oauth2)
- [ ] GitHub 

## ブランチ
ブランチ名:  feat/front-sns-auth
https://github.com/aiirononeko/languageMemoApp/tree/feat/front-sns-auth

**Comment by H37kouya** [comment]
# やったこと
遷移させる
``` js
document.location.href = `${process.env.baseUrl}/api/v1/auth/${provider}`
```
3回リダイレクトされることは確認できる

## エラー
### Github
スクリプト上のどっかにlocalhost:3000が埋め込まれてる。

![コメント 2020-06-21 162605](https://user-images.githubusercontent.com/46477357/85219119-ed612d80-b3db-11ea-8bd5-fb3290061143.png)
![コメント 2020-06-21 162549](https://user-images.githubusercontent.com/46477357/85219120-ee925a80-b3db-11ea-8b96-09fcc0974da0.png)


### Google
エラー 400: invalid_request
device_id and device_name are required for private IP: http://192.168.99.100:3000/omniauth/google_oauth2/callback

![コメント 2020-06-21 162455](https://user-images.githubusercontent.com/46477357/85219095-c60a6080-b3db-11ea-9d87-3f85830a935e.png)
![コメント 2020-06-21 162445](https://user-images.githubusercontent.com/46477357/85219097-c6a2f700-b3db-11ea-9dff-d31d3f35516e.png)

**Comment by H37kouya** [comment]
参考記事

https://qiita.com/ngron/items/7ff5a1114e8e3daaa243

**Comment by H37kouya** [comment]
GoogleとGitHubは遷移先URLをサービス上で決めている。

対策案
1. 新しいkeyを生成する。
2. Macユーザーに任せる。
3. 「自分のHOSTファイルを触る」か「dockerを別の方法で起動する」で無理やり、URL(localhost:3000)を再現する。

[Nuxt.jsのAuth ModuleでOauthによるログイン機能実装](https://noumenon-th.net/programming/2019/08/30/auth-modules/)

**Comment by Kanezoh** [comment]
とりあえずグーグルから一つずつ着手するということでよろしいですか？
前提として。サービスでコールバックURLを登録する必要があり、現在は全サービスlocalhost:3000で登録しています。先ほどこうやさんのプライベートIPを登録しようと思いましたが、どうやらグーグルではプライベートIPでの指定はできないようです。
![スクリーンショット 2020-06-21 16 59 30](https://user-images.githubusercontent.com/47489839/85219700-f56f9c00-b3e0-11ea-9a22-1239340e8b49.png)

**Comment by Kanezoh** [comment]
### 0703検証

ログインに必要な情報をリダイレクトさせたいURLのパラメータに入れて表示することに成功した。
動画はSlackに挙げたものを参照。
フロント側でSNS認証のリンクを`/auth/google_oauth2?auth_origin_url=[リダイレクト先URL]`のような形式にすると良さそう。
現在はこのauth_origin_urlをサーバー側で勝手に追加している。まあサーバーでやってもいいかな？

参考: https://note.com/mumii/n/n175e0d4d6f15
