### ISSUE TITLE
サイドバーでusernameが変更されたとき、リアクティブに変更されない

### ISSUE THREAD

**Issue by H37kouya** [aiirononeko/languageMemoApp#199]
# 概要
/settings/user-nameでusernameが変更されたとき、sidebarのマイページへのURLがリアクティブに変更されない

**Comment by H37kouya** [comment]
computedでObjectやarrayを使う場合、直接値を更新してはいけない。
値を更新するときはコピーをしてから行うことで感知できるようになる。

たぶん、直接値を変更しても、内部でアドレスが変わらないからかな？(テスト書いたときもこんな漢字の問題があった気がする。)
ようするに、computedでは、非破壊的な書き方をすること！！

``` js
computed: {
   gomi() {
      const data = this.data
      data.to = "newLink"
      return data
   },

   perfect() {
      const data = Object.assign({}, this.data)
      data.to = `/${this.username}`
      return data
   }
}
```

**Comment by show-coco** [comment]
@H37kouya はい！すんましぇん!!!!!!気をつけます。ありがとうございます👍

**Comment by H37kouya** [comment]
あ、このコード書いたの多分、僕......
自分が忘れないようにするために書いた......
