### ISSUE TITLE
SNS認証後の細かい修正点

### ISSUE THREAD

**Issue by show-coco** [aiirononeko/languageMemoApp#217]
- [x] SNS認証した後に設定済みのアイコン画像が表示されない
- [x] SNS認証した後、初回時にusername編集画面へ遷移
- [x] Signupページからsnsでログインできない

**Comment by H37kouya** [comment]
<UserSnsBtnGroup>の修正。
sns認証成功時に マイページでSNSのアイコンが表示されるようにする。
