### ISSUE TITLE
エラー処理を記述していない、@nuxtjs/axiosを使用する

### ISSUE THREAD

**Issue by show-coco** [aiirononeko/languageMemoApp#56]
https://github.com/aiirononeko/languageMemoApp/blob/c4e2d516ce80e76bc0596ad58443d5017b469056/frontend/pages/user/sign_up.vue#L56-L63

**Comment by H37kouya** [comment]
@nuxtjs/axiosが入ってるので、
このファイル内で、axiosをimportする必要は無い。
L57でthis.$axios.postにすればaxiosは使うことが出来る。

**Comment by show-coco** [comment]
### 質問
baseURLを設定しようとして、[Axios Module: baseURL](https://axios.nuxtjs.org/options#baseurl)を参考に以下のように設定しました

nuxt.config.js:
```javascript
axios: {
    baseURL: "https://localhost:3000"
},
```

ですが、Undefinedとなります
```javascript
console.log(this.$axios.baseURL) =>Undefined
```

原因わかりますか？

挙動としては、[module.js](https://github.com/nuxt-community/axios-module/blob/932abc071b1e1bb64e8d8fc1fdd6e6f9ceb99b5a/lib/module.js#L36)のbaseURLが上書きされるはず？

**Comment by show-coco** [comment]
$axiosのデフォルトで設定されているものは以下のように指定しないとけないみたいですね。
[github: axios Config-Defaults](https://github.com/axios/axios#config-defaults)

```javascript
this.$axios.defaults.~~~
```

今回はデフォルトの[baseURL](https://github.com/nuxt-community/axios-module/blob/932abc071b1e1bb64e8d8fc1fdd6e6f9ceb99b5a/lib/module.js#L36)を上書きしているため、次のように書かないといけなかったみたいです

```javascript
console.log(this.$axios.defaults.baseURL);
```
