### ISSUE TITLE
テストの導入

### ISSUE THREAD

**Issue by show-coco** [aiirononeko/languageMemoApp#63]
# やること
[NuxtJS-開発ツール](https://ja.nuxtjs.org/guide/development-tools/)と[NuxtJS-テスト](https://ja.nuxtjs.org/examples/testing/)を参考にテストを導入

テスティングフレームワークは**AVA**を使用予定
[github-avadocs](https://github.com/avajs/ava-docs/blob/master/ja_JP/readme.md)

**Comment by H37kouya** [comment]
> # やること
> [NuxtJS-開発ツール](https://ja.nuxtjs.org/guide/development-tools/)と[NuxtJS-テスト](https://ja.nuxtjs.org/examples/testing/)を参考にテストを導入
> 
> ~~テスティングフレームワークは**AVA**を使用予定~~
> ~~[github-avadocs](https://github.com/avajs/ava-docs/blob/master/ja_JP/readme.md)~~

# やること
Jestを導入予定。
[Jest公式](https://jestjs.io/ja/)
[Jest を使用した単一ファイルコンポーネントのテスト](https://vue-test-utils.vuejs.org/ja/guides/testing-single-file-components-with-jest.html)

**Comment by H37kouya** [comment]
# テストのコマンド
以下のコマンドでテストが走ります
`npm run test`

**Comment by show-coco** [comment]
お疲れ様です👍

**Comment by H37kouya** [comment]
# 導入時に参考にした記事
- [公式サイトvue-test-utils](https://vue-test-utils.vuejs.org/ja/)
- [Jestのセットアップ](https://qiita.com/rhistoba/items/6e90e2c51e8ad1875ac0#jest%E3%81%AB%E3%82%88%E3%82%8B%E3%83%86%E3%82%B9%E3%83%88)
- [vue-test-utils-jest-example
](https://github.com/vuejs/vue-test-utils-jest-example)
- [Vuetify と jestの設定](https://uyamazak.hatenablog.com/entry/2020/01/30/134757)
