### ISSUE TITLE
StoryBookの導入

### ISSUE THREAD

**Issue by show-coco** [aiirononeko/languageMemoApp#71]
# なぜ導入するか
- コンポーネントのスナップショットによってUI構造についてテストができる
- 他の開発者がサーバ立てなくても、UIの確認ができる
- コンポーネントのAPI仕様のまとめ
などなど

**Comment by H37kouya** [comment]
# StoryBook 公式へのリンク
[StoryBook](https://storybook.js.org/)
[Storybook for Vue](https://storybook.js.org/docs/guides/guide-vue/)

**Comment by H37kouya** [comment]
# コマンド
自動で設定してくれるらしい。
``` bash
$ npx -p @storybook/cli sb init
```

## 参考
[【Nuxt.js / Storybook】インストールとaddonの導入まで(StoriesOf APIではなく最新ver推奨のCSF記法で)](https://qiita.com/kamicop/items/887d9dc40facaa43eed7#133-sassscss%E3%81%AE%E4%BD%BF%E7%94%A8%E8%A8%AD%E5%AE%9A%E3%81%8B%E3%81%A4%E3%82%B0%E3%83%AD%E3%83%BC%E3%83%90%E3%83%AB%E3%81%AAcss%E7%94%A8%E5%A4%89%E6%95%B0%E3%82%84mixin%E3%82%92%E8%AA%AD%E3%81%BF%E8%BE%BC%E3%82%80)
